### PR TITLE
Update silk and edge cuts

### LINKED ISSUE #26: Daughter board silk screen for half-swept inverted
Hi there, it appears the silk screening for the daughter board on the half swept is inverted, i.e. the indication for which rows of holes should be used for each side is backwards. This leads to VCC being shorted to reset if you follow the visual indication. Can I suggest clarifying the silk screening, or alternatively removing it and providing written and visual instruction? As a side note, the row of holes closest to the board edge is *very* close to the edge. Suggest moving the edge.cut out to the other graphical edge line.

Happy to do this, but am not up to speed with git. Fine with kicad though.

### PR DESCRIPTION
**Pull request by duckyb**
Fixes #26 

## Changelog
- Expand edge cuts to better fit the micro controller pads and silk
- Reduce amount of labels for micro controller silk (both sides)
- Change the labels for battery pads to B- and B+ on both sides
- Reduce overall amount of overlapping silk
- Improve clarity of micro-controller outline silk
- Update png to reflect changes
- Update gerber to reflect changes

## Preview
image

image

### CODE REVIEW

**Comment by bowlerhatman** [comment]
This looks much neater, but the screening is still on the wrong side of the board. The relevant labels should be visible from the top side, so in both cases the box outlines should be shifted to the other set of holes, and the RAW and other labels mirrored to the right.

**Comment by duckyb** [comment]
> This looks much neater, but the screening is still on the wrong side of the board. The relevant labels should be visible from the top side, so in both cases the box outlines should be shifted to the other set of holes, and the RAW and other labels mirrored to the right.

image

This is the top view of the PCB. As you can see the silk is coherent with the schematic.

@bowlerhatman

**Comment by bowlerhatman** [comment]
Except RAW is at the top right of the micro, and the front side silskreen marks it as being at the top left. Looking from the top, as in the shot above, shows the back side RAW at the top right, this indicates that the footprint is mirrored, as RAW should be at the top right on whichever side of the board you're viewing.

**Comment by duckyb** [comment]
> Except RAW is at the top right of the micro
@bowlerhatman 

Depends how you flip the micro controller board, that's why the ferris PCB instructs to install it "Face down".

The "Face down" text indicates that the components on the micro controller should be facing the ferris PCB and in this orientation the silk matches on both boards.

I hope this makes sense for you

**Comment by duckyb** [comment]
image

It should end up looking like so

**Comment by bowlerhatman** [comment]
Aah, I see now. On the version I printed, it only says Face Down on one side, so I figured it was a hangover from a non-reversible version. I was focused on the outlines in this new version, so missed the addition of the extra face down comment. This makes sense now. Out of curiosity, why mount it upside down?

Thank you for your time, I appreciate it!

**Comment by duckyb** [comment]
No worries. I fixed this issue by also adding the "Face down" instruction on both sides.

The orientation is a choice of the design that I didn't make, but some reasons could be:

- better protection for the MCU components against accidental damage especially during travel
- annoying bright LEDS of some mcu boards get hidden
- most other keyboards use this orientation
  - if people have other boards with mill-max hot swap micro controllers facing down they can use it here too

**Pull request merged**
